name: ClientCrasher
version: '${version}'
main: org.sysapp.runkang10.clientcrasher.ClientCrasher
api-version: '1.21'
load: STARTUP
authors: [ Runkang10 ]
description: The worst punishment for cheaters!

permissions:
  clientcrasher.use:
    default: false
    children:
      - clientcrasher.crash
      - clientcrasher.crashban
      - clientcrasher.crashunban

  clientcrasher.crash:
    default: false

  clientcrasher.crashban:
    default: false

  clientcrasher.crashunban:
    default: false

  clientcrasher.exempt:
    default: false

dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true
